### ISSUE TITLE
Download data capability

### ISSUE THREAD

**Issue by jrgwhiteford** [RobJN/regional-fes#33]
Provide a "download data" option so stakeholders can download data from the current view directly from the platform

**Comment by slowe** [comment]
@jrgwhiteford Shall I output a CSV file with rows for each of the regions in the current view (NUTS1 regions if that is selected, or GSPs if they are selected) with columns for each year? I can put the units in the column heading e.g.

```
Area,2020 (MW),2021 (MW),2022 (MW),2023 (MW) ...
East Midlands (England),5073.1,4855.0,4682.2,4624.6 ...
East of England,5759.1,5506.8,5310.3,5249.1 ...
London,6499.0,6227.9,6033.2,5976.0 ...
```

**Comment by jrgwhiteford** [comment]
Yes that works for me
