### ISSUE TITLE
Wider styling

### ISSUE THREAD

**Issue by slowe** [RobJN/regional-fes#35]
@jrgwhiteford @RobJN A few styling options (see screenshot below):
   1. The map interface can take up the whole browser width.
   2. A "hero image" header in the style of the [FES pages on the National Grid ESO website](https://www.nationalgrideso.com/future-energy/future-energy-scenarios).
   3. Potential placement for a "Download" button below the selection interface.
![Screenshot 2022-05-11 at 09-31-22 Regional Breakdown of FES 2021 Data (Electricity)](https://user-images.githubusercontent.com/299787/167805687-97b666f7-1f7d-4318-82b7-33b0d556da7c.png)

**Comment by jrgwhiteford** [comment]
These look like relevant and good changes.

**Comment by jrgwhiteford** [comment]
@slowe when zoom is fixed at 100%, I am struggling to fit everything into my screen (all of menu on the left and the map on the right)

**Comment by slowe** [comment]
@jrgwhiteford I'm not sure I follow. It shouldn't be worse that how it already was. It should have just made the map wider if the width allows. Can you screenshot the problem?

**Comment by jrgwhiteford** [comment]
@slowe you are right - issue was at my side
